# Generated by Django 3.0.4 on 2020-03-28 17:46

from django.db import migrations, models
import fake_or_real.models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_or_real', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='proof',
            field=models.ImageField(default='default_proof.jpg', upload_to=fake_or_real.models.scramble_uploaded_filename),
        ),
    ]
