# Generated by Django 3.0.4 on 2020-03-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fake_or_real', '0002_auto_20200328_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('choice', models.BooleanField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_vote', to='fake_or_real.News')),
            ],
        ),
    ]
